In [1]:
import sklearn as sns

from sklearn.datasets import load_iris

In [2]:
iris_dataset = load_iris()

In [3]:
print("Keys in iris_dataset: \n{}".format(iris_dataset.keys()))

Keys in iris_dataset: 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [4]:
print(iris_dataset['DESCR'][:193] + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive 
...


In [5]:
print("Target names:", iris_dataset["target_names"])

Target names: ['setosa' 'versicolor' 'virginica']


In [11]:
print("Feature names: \n",(iris_dataset['feature_names'])) 

Feature names: 
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [17]:
print("Type of data:",(type(iris_dataset['data'])))

Type of data: <class 'numpy.ndarray'>


In [20]:
print("Shape of data:",(iris_dataset['data'].shape))

Shape of data: (150, 4)


In [23]:
print("First five columns of data:\n",(iris_dataset['data'][:5]))


First five columns of data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [26]:
print("Type of target:",(type(iris_dataset['target'])))

Type of target: <class 'numpy.ndarray'>


In [28]:
print("Shape of target:", (iris_dataset['target'].shape))

Shape of target: (150,)


In [30]:
print("Target:",(iris_dataset['target']))


Target: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
